import "./globals.css";
import Sidebar from "./(components)/Sidebar";
import { Providers } from "./providers";
export const metadata = {
  title: "Goal Rock",
  description: "Generated by Omer",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen max-h-screen w-screen flex flex-row">
        <Providers>
        <Sidebar/>
        {children}
        </Providers>
      </body>
    </html>
  );
}
