import "./globals.css";
import Navbar from "./(components)/Navbar";

export const metadata = {
  title: "Goal Rock",
  description: "Generated by Omer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
